### PR TITLE
added GitHub workflow and other enhancements

### LINKED ISSUE #3: other operating systems
Not everyone uses windows, how about for linux and mac as well?

### PR DESCRIPTION
**Pull request by FibreFoX**
This should fix #3 (for real this time).

Small overview what this PR improves:
- added support for Godot 4.0.x too (using a simple macro for the changed typedef, and some SCons magic with `compatibility_minimum` version)
- removed all pre-built binaries, as they will now generated by Github Action runners
- reworked the file structure to avoid duplications, e.g. the icon inside the actual addon folder (will be generated/copied via SCons)
- renamed several places to `gdTree3D`, because it was confusing sometimes (even was mentioned in the video https://www.youtube.com/watch?v=4aPkTQuo53E where this Godot extension was mentioned), except the generated library filename (could not figure it out)
- introduces docker-based build image for generating Windows and Linux binaries (made it a bit more easy to create them fast locally)
- and of course generating binaries for MacOS, Linux and Windows for several CPU architectures
- automatic DRAFT RELEASE creation when a new git tag was created, which includes all the generated ZIP packages, separated into "demo project" and "only addon"

Details about the Github Actions workflow:
Artifacts can only be downloaded when being logged into some Github account (seems to be a quite new restriction, there is an open issue, which I forgot to bookmark). Checking for it can be reached via the navigation, where all the workflows then are listed:
grafik

The draft release is created when a git-tag is created starting with the letter `v` (e.g. `v1.0.0`), and can be found in the sidebar navigation:
grafik
grafik

Important: I do not have access to any Apple Silicon/Apple-ARM-CPU system, where I could check the "Universal 2"-MacOS-binary. If this is faulty (like I had problems with all the 64bit binaries before, see https://github.com/JekSun97/gdTree3D/pull/5#issuecomment-2308728000), just ping me, so I can fix it fast.

I tried to not change too much, and did add a lot of commits (sorry for the commit noise). But I had a ton of fun creating this workflow.

If there are any more changes, feel free to contact me, or write me here via this PR.

### CODE REVIEW

**Comment by FibreFoX** [comment]
I tried to add good comments and references across my changes, hopefully they help.

**Comment by FibreFoX** [comment]
~~There still is something wrong with the icon ;) let me fix that before you hit "merge"!~~

~~Problem right now:~~
grafik

EDIT: fixed, see comments below

Maybe that was the reason for the weird "gdTree3D" vs "Tree3D" naming?

**Comment by FibreFoX** [comment]
Okay, found the issue .... and it's somewhat unexpected, ~~maybe this is a (known) Godot bug~~:
~~it depends on the "Type", when changing it to "gdTree3D" it works with my changes~~
grafik

EDIT: I found https://github.com/godotengine/godot/pull/75472 which points to the `[icons]`-section ... thats why it did not find the icon after changing to gdTree3d...

@JekSun97 as this is your gdExtension ... do you prefer the name "Tree3D" or are you okay with "gdTree3D"?

**Comment by JekSun97** [comment]
@FibreFoX  Thanks for the work done on GitHub Action! For me this is a particularly complex and unexplored topic :D

I would like to keep the name "Tree3D" instead of "gdTree3D" as it matches the naming of nodes in Godot Engine, I used gd at the beginning of the name so people would understand that it is related to Godot, maybe I should correct this confusion in README.md

**Comment by FibreFoX** [comment]
@JekSun97 I am more used to GitLab, so using GA was an adventure for me too ;)

Regarding the name: sure, will change it, please wait some time for the changes before merging ;) I will change the README accordingly, will be part of my changes (less for you to do :D)

**Comment by FibreFoX** [comment]
@JekSun97 I think my changes are complete now, please verify that my changes are working for you. Here the link to the workflow for my last commit (you can find the binaries there): https://github.com/FibreFoX/gdTree3D/actions/runs/10656732794

EDIT: of course I had to fix the icon again ;)

**Comment by JekSun97** [comment]
Thank you!

**Comment by FibreFoX** [comment]
@JekSun97 just remember, when creating a git-tag, there will be automatically a draft-release created ;) no more manually adding the files

**Comment by JekSun97** [comment]
> @JekSun97 just remember, when creating a git-tag, there will be automatically a draft-release created ;) no more manually adding the files

Are they built from the main branch?

is the workflow like this?:
1. Add fixes\new features to the main branch
2. Create a release (without adding dll files)

Will the release contain all the built dll files for the operating systems?

**Comment by FibreFoX** [comment]
Right now this workflow reacts on 2 events:
- git push to ANY branch https://github.com/JekSun97/gdTree3D/blob/f34effd250a1bab6af0df09c6e61b740f83a4af0/.github/workflows/build-with-github.yml#L6
- when a git-tag gets pushed starting with the letter "v" https://github.com/JekSun97/gdTree3D/blob/f34effd250a1bab6af0df09c6e61b740f83a4af0/.github/workflows/build-with-github.yml#L8

A github release in "draft"-state will be created for every git tag this workflow is running: https://github.com/JekSun97/gdTree3D/blob/f34effd250a1bab6af0df09c6e61b740f83a4af0/.github/workflows/build-with-github.yml#L162

Git tags can be created on any git commit, and are not "branch"-oriented.

These "draft"-state releases will contain ALL the generated binaries, means for all Godot versions, see the screenshot:
363338619-e2ff691a-6ce3-4107-9b64-7b6331f14f66
These ZIP files contain all the binaries for all operating systems and all CPU architectures (at least all that are getting built by the workflow)

So all it requires from your side is to push normally, and when you feel finished, just create a git tag for that commit you like. After that (and the workflow having processed everything, which takes about 20 minutes), you only need to adjust the description of the "draft"-state release, and release that one.

**Comment by FibreFoX** [comment]
@JekSun97 Just saw the new release ;) the created draft-release already contained different ZIP files, which contained the complete addon and the demo-projects. Did you not use them on purpose?

**Comment by FibreFoX** [comment]
Tiny note: I see that you are not using proper git tags, please only use anything that starts with `v`. The current new release starts with `Tree3D_v` ;) no need for the product name being part of the git tags. Thats why no draft-release was created, in addition to that, the 64bit version for Godot4.3 is missing for Windows and some MacOS binaries
grafik

**Comment by JekSun97** [comment]
@FibreFoX  I was a bit hasty and as usual got confused in all this :D, for the next release, before its release, I will need to contact you for step-by-step instructions.

**Pull request merged**
