### PR TITLE
Reuse `twig_inst`.

### LINKED ISSUE #1: Duplication problem
I noticed a problem when duplicating a Tree3D node using Ctrl+D: if we change any leaf or branch value, we see that the old mesh of the duplicate node remains and it looks like one tree is overlaid on top of another.

This multi-level tree disappears after the project is restarted.

I don't know how to solve this problem yet, if anyone has any ideas, I'd be glad for your help.

### PR DESCRIPTION
**Pull request by Daylily-Zeleen**
@JekSun97 I received your email and create this pr to solve your problem.

Fix [#1](https://github.com/JekSun97/gdTree3D/issues/1).

Like I said in [#9282](https://github.com/godotengine/godot-proposals/issues/9282#issuecomment-2466754520).
Just reuse the internal node instead of removing it and adding a new one.

By the way, this is greate plugin!

### CODE REVIEW

**Comment by FibreFoX** [comment]
So this PR solves multiple issues, right?

**Comment by Daylily-Zeleen** [comment]
> So this PR solves multiple issues, right?

I dont know, I am invited to sovle [#1](https://github.com/JekSun97/gdTree3D/issues/1) only.

**Comment by JekSun97** [comment]
@Daylily-Zeleen  Wow, I didn't think that the response to help would be so fast! 
After looking at the changes in the code, I realized that I still have to delve into the knowledge of godot-cpp, thank you very much, this error has greatly disrupted the progress of the plugin, I will check everything at home and post it ^_^

**Comment by JekSun97** [comment]
@Daylily-Zeleen Strange, the duplication error still persists:

https://github.com/user-attachments/assets/98831f30-6ad5-44e8-b41c-11607a99ae18

**Comment by Daylily-Zeleen** [comment]
@JekSun97 Refer to my [comment](https://github.com/godotengine/godot-proposals/issues/9282#issuecomment-2466754520), this solution need some commits of godot and godot-cpp.
They are merged in 4.3, in orthor words, this pr will require this plugin to use at least godot 4.3 both godot and godot-cpp.

**Comment by JekSun97** [comment]
> @JekSun97 Refer to my [comment](https://github.com/godotengine/godot-proposals/issues/9282#issuecomment-2466754520), this solution need some commits of godot and godot-cpp. They are merged in 4.3, in orthor words, this pr will require this plugin to use at least godot 4.3 both godot and godot-cpp.

Got it, unfortunately then I'll have to reduce the minimum supported version of Godot

**Comment by FibreFoX** [comment]
@JekSun97 what is your plan on the version? as far as I understand, this issue is in combination with Godot itself, right? Should #1 then be reopened then, because the issue isnt solved for earlier versions?

@Daylily-Zeleen do you know if there is any backport earlier than godot 4.3 ?

**Pull request merged**
